language: rust
rust:
  - nightly
  - beta
  - stable
sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - nightly

env:
  global:
    - CRATE=maud-pulldown-cmark
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
    - secure: e6cF8uMs8fC2HoOMbxdJeyymPT/SJJHHhhh+sfzGw8onNgOfC66w3FCqg8g6UL8bjTLxgHYMcUZD+P+bJHQr9mrNWvgYB/VMPJrXWjCa+pn9R3ZYhOtrXRV23+y5PVUHdx4/DOnY63lhS2T8205VjEbyn3AlciAZDUVTZ0jtjXdVMiewwGNCRB7TUjAlBS1lOMrNv7xwVPehzQWc0U7aDEj0ZBMAmWTGfDsfO860iwngtibaN6m6ptXz56/jvmaUNIRYOlhmcqs4S6VoLVos46XC7YFyP9BDJvg9K7qC9wIxgdk10qjrbW8nChITOhKclMKZ55UvnA7PpKT2EoWU19GwRgP+z7LGh4SKvH/hgajS3xfCfxoj8UYCazkpOhbnaTTJjwoKLZ/In4b8IEsLUwUcSqjWUVVfYiLSC1AaiFI2+TKQ7UMrDqYVwRe3RXS18E3ABaTkp6D2py33eNMI6csclnSGUMwZLYWF/2TG9ZjeW9YcEF6GqrtUgXzRVbKeRICxCVdrkZYbma7RBOR9TuET9vOvyPJ9QX+aZf6j0xhPx9V1RgRsadY1D/Cn6NGnSivjrFJZgcQoagvf+ypjvP8mUPDqdD3vpCkfpoMxFQGl7GyDYWonXDFDhYItxR8cOET8Nwhk6ekR6oUKezkxHgeUIxGvv/ZzJgZd0JxlI5U=
    - secure: cyT+jBKqmkKIXezVHxKtMN9oQ+c02DBHRVmMlMZxmxzY693KW3dtkVxoxjBOLiyeitMTfSIkQFsfTUPLLi94AEeGOYuqG/FBxVXrfC6bsRZOh9CEKOx3WtVH0p1BqY8/sQ0JZQB+P76U7lHMI8ijewp8F6ZDH241vbQCyhsMMfbPlZiNxqp5UFiYAoaJAJ6BFpbCURYXm1xALfZbo6Ght0vM1ys5442GBI7GlvJYzDg9Lx2s6vutvDjnHO4y3FoG6ufPRy07C7/qUQSRpxUIXnEPRx8rGWVcuO9B9wG4wNImbGoB+lsEI3USnYd3RbXPpdaitMRy4qGJQA/clON1gXMwoORn5bXgy0usqPeycmlr/y5kbERKeFybcjoV8vN0CMA3hpYsZUPLrwe+X1aILfoxdEqWJ3mpbuYLnp93+pQZYc06OnSq60kgJ+zOrvyJgD5/L8Kq/Uo5IVz3K+RuiN+nIyFZ8MD+ztbUNuc12HE9i1ZKT0CYmjpnCoRtHEsKrJaPf7xucTYn+6Htzy/l4qhavOkH3yADtnWbdwHPSi3QE8bsy55hl7F5AnIxjoVMWBQF+4/rYasYkIoe2utoD7vFGmsm1fqZCH7MyChImeGOoR1UhQt5qcadSJNrQUZQ61hEb5MVa27FX4rA5LssJUW8pvU8MwY5orgFivWz4aw=

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo build
  - travis-cargo test

before_deploy:
  - travis-cargo doc
  - travis-cargo package

deploy:
  provider: releases
  api-key:
    secure: WbISro9D3LHjX/MVg0Af34y4kavviph0SRlyJrd6Py/dp0L/hMq6Cq6TqZv8FwgBfHkoW1DLZgeeToypNVPX+a5wZyRq4KM1wp93o0mf3nGi7l5zQ+eqhEMItbSn0Tuuvm90m6BjMUV63HctHfct1dkDZITWjzhXoqmUwbxgYzeIZofmaD8QcmUC8go7boUdM3hVNHlVTtDObuUXdkr5wIV+lb5NahuinFb15YQrt8RI35Tm2zj9xf8wPFo2S2opWBZpAuHQWA7U6dcwOv8pcVmfWXSKzDBQpZ/nAytzrLYsPUbNhaY7ZiUJ0ETY/Vn7c929mBruOTE7ZLWyE2J1juSf0Jw9PrDkGidG23EEXJPnQq+eXD5mrLEHC8AXYcfcNrwTsWQvIM4lSNErBp5Q0ct0PVciSJrMp+unMb66vBPD/mB+DqxnQ0K+4B8yvA8qoieuxHZbFrvVP5vh8mDXPCGtG9FTzm8I4JOoLjNLpu+ik4yRA2xWL2vBHqpBoZT+2gg7sqJ7Ct92YKbNXKii0Klakzyp6IvfFjIli+lqPY6OZ10blQ1sBtD7B3jTpNAUrfdwjlv6kB4O8+3LTntzOC+w9Mc8lnrhilG1NkCvHRDwV3sKqO69zUoSj/qMf6WHqH6ZQvjJnsrji/1t28H9UeW3/9Q2DqZ2nbH0J94c9sQ=
  file: target/package/$CRATE-$TRAVIS_TAG.crate
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"

after_deploy:
  - cargo publish --token "$CRATES_IO_TOKEN"
  - ./ci/save_credentials.sh "$GITHUB_TOKEN" "$TRAVIS_REPO_SLUG"
  - ./ci/publish_docs.sh "$TRAVIS_TAG" "$CRATE"
