language: rust
rust:
  - nightly
  - beta
  - stable
sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
    - secure: e6cF8uMs8fC2HoOMbxdJeyymPT/SJJHHhhh+sfzGw8onNgOfC66w3FCqg8g6UL8bjTLxgHYMcUZD+P+bJHQr9mrNWvgYB/VMPJrXWjCa+pn9R3ZYhOtrXRV23+y5PVUHdx4/DOnY63lhS2T8205VjEbyn3AlciAZDUVTZ0jtjXdVMiewwGNCRB7TUjAlBS1lOMrNv7xwVPehzQWc0U7aDEj0ZBMAmWTGfDsfO860iwngtibaN6m6ptXz56/jvmaUNIRYOlhmcqs4S6VoLVos46XC7YFyP9BDJvg9K7qC9wIxgdk10qjrbW8nChITOhKclMKZ55UvnA7PpKT2EoWU19GwRgP+z7LGh4SKvH/hgajS3xfCfxoj8UYCazkpOhbnaTTJjwoKLZ/In4b8IEsLUwUcSqjWUVVfYiLSC1AaiFI2+TKQ7UMrDqYVwRe3RXS18E3ABaTkp6D2py33eNMI6csclnSGUMwZLYWF/2TG9ZjeW9YcEF6GqrtUgXzRVbKeRICxCVdrkZYbma7RBOR9TuET9vOvyPJ9QX+aZf6j0xhPx9V1RgRsadY1D/Cn6NGnSivjrFJZgcQoagvf+ypjvP8mUPDqdD3vpCkfpoMxFQGl7GyDYWonXDFDhYItxR8cOET8Nwhk6ekR6oUKezkxHgeUIxGvv/ZzJgZd0JxlI5U=
    - secure: cyT+jBKqmkKIXezVHxKtMN9oQ+c02DBHRVmMlMZxmxzY693KW3dtkVxoxjBOLiyeitMTfSIkQFsfTUPLLi94AEeGOYuqG/FBxVXrfC6bsRZOh9CEKOx3WtVH0p1BqY8/sQ0JZQB+P76U7lHMI8ijewp8F6ZDH241vbQCyhsMMfbPlZiNxqp5UFiYAoaJAJ6BFpbCURYXm1xALfZbo6Ght0vM1ys5442GBI7GlvJYzDg9Lx2s6vutvDjnHO4y3FoG6ufPRy07C7/qUQSRpxUIXnEPRx8rGWVcuO9B9wG4wNImbGoB+lsEI3USnYd3RbXPpdaitMRy4qGJQA/clON1gXMwoORn5bXgy0usqPeycmlr/y5kbERKeFybcjoV8vN0CMA3hpYsZUPLrwe+X1aILfoxdEqWJ3mpbuYLnp93+pQZYc06OnSq60kgJ+zOrvyJgD5/L8Kq/Uo5IVz3K+RuiN+nIyFZ8MD+ztbUNuc12HE9i1ZKT0CYmjpnCoRtHEsKrJaPf7xucTYn+6Htzy/l4qhavOkH3yADtnWbdwHPSi3QE8bsy55hl7F5AnIxjoVMWBQF+4/rYasYkIoe2utoD7vFGmsm1fqZCH7MyChImeGOoR1UhQt5qcadSJNrQUZQ61hEb5MVa27FX4rA5LssJUW8pvU8MwY5orgFivWz4aw=

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - sh -c 'if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then grep -v "maud_macros" Cargo.toml > Cargo.toml.new && mv Cargo.toml.new Cargo.toml; fi'

script:
  - travis-cargo build
  - travis-cargo test

before_deploy:
  - travis-cargo package

deploy:
  provider: script
  script: cargo publish --verbose --token "$CRATES_IO_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"
