language: rust
rust:
  - nightly
  - beta
  - stable
sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - nightly

env:
  global:
    CRATE: maud-pulldown-cmark
    # - secure: CRATES_IO_TOKEN
    # - secure: GITHUB_TOKEN

script:
  - cargo build --release --verbose
  - cargo test --verbose

before_deploy:
  - cargo doc --verbose
  - cargo package --verbose

deploy:
  provider: releases
  # api-key:
    # secure: YUXdO4SZv3+Cm550DGc9WLYRWHaBC4LWYkJK2sbR+GjSkNSvKHfxOe0+pDzJGHNY+QOWKal37H6bCGmk43xHgwWExb0nZ+Vp1nJG/nUeTcglF4tYSX+GJQEOioj1YmaOai0NuJ1peDS8TZXYmbghMc4vnLUnYg7t4gQ3m8M/fVY=
  file: target/package/$CRATE-$TRAVIS_TAG.crate
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"

after_deploy:
  - cargo publish --token "$CRATES_IO_TOKEN"
  - ./ci/save_credentials.sh "$GITHUB_TOKEN" "$TRAVIS_REPO_SLUG"
  - ./ci/publish_docs.sh "$TRAVIS_TAG" "$CRATE"
