[package]
name = "maud-pulldown-cmark"
version = "0.0.1"
authors = ["Wim Looman <wim@nemo157.com>"]
description = "An adapter between maud and pulldown-cmark"

documentation = "https://nemo157.com/maud-pulldown-cmark"
homepage = "https://nemo157.com/maud-pulldown-cmark"
repository = "https://github.com/Nemo157/maud-pulldown-cmark"

readme = "README.md"
keywords = ["maud", "markdown", "pulldown-cmark", "adapter"]

license = "MIT/Apache-2.0"

[dependencies]
pulldown-cmark = "0.0.5"
maud = "0.7.3"
